<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\clici.Core\clici.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="clici.App.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>clici</AssemblyName>
    <RootNamespace>Clici.App</RootNamespace>
    <ApplicationIcon>Assets\clici.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
